### PR TITLE
Adding permitted-reagent-categories to ProtocolStep

### PR DESCRIPTION
**Pull request by upli**

### CODE REVIEW

**Comment by remiolsen** [comment]
@Galithil Are you maintaining this repository and can you look at this PR?

**Comment by remiolsen** [comment]
@upli Can you please add a description to this pull request? We don't really know what it does.

**Comment by ewels** [comment]
If you [ignore the whitespace changes](https://github.com/SciLifeLab/genologics/pull/224/files?w=1) in this PR, you can see that it just adds a single new line of code:

```python
permitted_reagent_categories = NestedStringListDescriptor('reagent-category', 'permitted-reagent-categories')
```

@upli - could you please describe what this new entity is, and why you need it? Thanks!

**Comment by ewels** [comment]
Closing this issue for now due to lack of response. Happy to reopen if we can have a conversation about the proposed addition.

**Pull request closed without merging**
