### PR TITLE
setting a string attribute adds the tag to XML

### PR DESCRIPTION
**Pull request by paalmbj**
I'll send you some pull requests, trying to split up my changes into manageable chunks. Feel free to accept or reject of course.

The rationale for this one is that some XML tags are not present in the data returned by a GET, but could still be added in a PUT. Example: the <preset> tag in steps/{limsid}/details (to be added in a following pull request)

### CODE REVIEW

**Comment by Galithil** [comment]
I'm not sure I see the scope of this. Do you have an example so I could understand ?

**Comment by paalmbj** [comment]
I'll get back to this one later

**Comment by paalmbj** [comment]
The main use from my side is in steps/{limsid}/details for the preset tag (the tag name got lost in the formatting in the previous comment). I have the step details as an entity (will tidy that up soon, and make a pull request). Anyway, it's defined as:

    class StepDetails(Entity):
        """<snip>"""
        preset            = StringDescriptor('preset')

All the other info in steps/.../details is hard to represent, as we'd have to modify the UdfDictionaryDescriptor etc. But the only way to get to the preset is through the StepDetails. So when there's no preset defined for a step, no preset tag is returned. But it's still possible to set one through the API, by adding the tag, with a text value. The suggested change to StringDescriptor allows me to add a preset tag. 

This should be the case for any tag with the following properties, but I've only encountered the preset so far:
Always returns with GET: No
Updatable with PUT: Yes
Required for PUT: No, if not provided, an existing preset selection will be cleared 

I'd also like to add an "instance.get()" at the start of the put(), as that will allow assignment before any property is read, but I'll leave that for later.

**Comment by Galithil** [comment]
Handled in another PR.

**Pull request closed without merging**
