### PR TITLE
Adding Automations

### PR DESCRIPTION
**Pull request by mayabrandi**
Adding the Automation class to the package.

### CODE REVIEW

**Comment by Galithil** [comment]
Is there a reason why the 'string' value is stored in an attribute named "bash" ? 
If it is named 'string' then someone with access to the online doc will correctly assume that the 'string' atribute correlates to the 'string' key. 
If you wish to also have a bash key linking there, I don't mind, but it would be nice to have least keep consistent with the xml schema.

**Comment by mayabrandi** [comment]
I know! I was hesitating when naming it bash, but I just thought string was not descriptive enough. What it stores is the whole "bash string" for the automation. But Im happy to change from bash to string if you thinks so!

Regarding process-type, I just thought I had seen at some other place in the code that he used "steps" instead of process_types. But now I cant find it.  Ill switch from steps to process_type. @Galithil

**Comment by Galithil** [comment]
Looks good so far. There's one last thing you need to do, though, you need to update the https://github.com/SciLifeLab/genologics/blob/master/genologics/version.py file with the new version (0.4.6).

That way, if you write code that requires the automation endpoint mapping, you can request for the proper version in your requirements.

**Comment by mayabrandi** [comment]
Done @Galithil  
👍

**Comment by mayabrandi** [comment]
Tackitack! 

Skickat från min iPhone

**Pull request merged**
