### PR TITLE
Reagent lot and kit

### LINKED ISSUE #151: Change to StepActions
Hi,
I need to rework the way Step stores actions and that might results in backward incompatible changes to the API.
I was wondering how much this would affect you and the potential users of the API as it seems to be still work in progress
Cheers
Tim

### PR DESCRIPTION
**Pull request by tcezard**
This add functionalities to:
 - access Step object from Process (they share the same id)
 - access parse ReagentLot/ReagentKit and access from Step
 - refactor StepActions, add support for next_actions
The refactoring of StepActions should be backward compatible.

There is also a fix for building from git in python 3

This closes #151

### CODE REVIEW

**Comment by Galithil** [comment]
I don't think this changes anything in the API, it only adds next_actions and reagent lots/kits, right ?

**Comment by tcezard** [comment]
Yes that's right, it also adds the handy step link in Process.

**Comment by Galithil** [comment]
I'd be careful about that one, I remember seeing processes that did not
have a step counterpart.

**Comment by tcezard** [comment]
Ok, hold on merging this then I'll query genologics.
I can't find any information about that in the documentation.
This said I would really like to have that link as Processes are easy to find and Step contains useful information.
It might just be a case of putting the link in a try, except block and return None if no Step exists.

**Comment by Galithil** [comment]
It won't impact me in the least, and I doubt anyone but you have scripts
making heavy use of this, so I don't mind merging it. Keep in mind that I
the processes in question might belong to an older version of the LIMS.

**Comment by tcezard** [comment]
I got this response from genologics when I asked if the Step id and the Process id are always the same.

> Yes, they will be the same. The process endpoint is older and process functionality is being moved over into the steps endpoint. In the [distant] future the process endpoint will be deprecated.

I think  we can assume that it should be good for now.
Happy to revisit if that causes issue in the future.

**Comment by Galithil** [comment]
Yep, we can't guarantee compatibility for really old versions anyway if the deprecate processes. I hope they won't though, since they guaranteed that the api would always be retro-compatible.
But this is not the place to discuss this.

**Comment by Galithil** [comment]
It also has been deployed on Pypi.

**Comment by abstratt** [comment]
@Galithil @tcezard 

> I'd be careful about that one, I remember seeing processes that did not have a step counterpart.

IIRC, if you run a process in the legacy UI (which does not understand protocols and protocol step configurations), it won't have a corresponding step.

**Pull request merged**
