### PR TITLE
Fix missing import

### PR DESCRIPTION
**Pull request by tcezard**
Forgot an import in previous PR
I don't know if you want me to increment the version for that.

### CODE REVIEW

**Comment by Galithil** [comment]
in scope import... I'm really not thrilled about that.
Isn't the PlacementDictionaryDescriptor only used in Containers ?

**Comment by tcezard** [comment]
I know it's not the prettiest but it the most common way to avoid cyclic imports.
It is only using in container but imported at the top of  entities.
The alternative solution is to import  genologics in descriptors and instantiate Artifact, Process and Container with their full path like this.
```python
import genologics
genologics.entities.Artifact()
genologics.entities.Container()
genologics.entities.Process()
```
Not my preferred solution but it will work.

**Comment by Galithil** [comment]
mmmmmh. Not a fan either. I guess splitting entities and descriptors wasn't as straightforward as expected. let's hope it won't get farther than this.

**Comment by tcezard** [comment]
Yeah I agree. 
Are you releasing/replacing the pypi version?

**Comment by Galithil** [comment]
yes, it's called 0.3.6b0.post0 and is the only visible version in there. I
wanted to avoid having non obvious versions in there, but that will have to
do.

**Pull request merged**
