### PR TITLE
Split entities

### LINKED ISSUE #170: Split entities in two
Hi
I want to split entities.py into entities and descriptors
I don't think it should affect anybody as the descriptors should not be used outside of the entities.
I'm not sure what to do with SampleHistory: should it stay in entities?

Thank

### PR DESCRIPTION
**Pull request by tcezard**
This PR does not contain any functional changes but splits entities.py into three files:  constants.py, descriptors.py and entities.py.
All the classes uses by the clients of the genologics stays in entities so the backward compatibility should be maintained.

I also ran some automated code reformatting which makes the resulting diff very large.

closes #170

### CODE REVIEW

**Comment by Galithil** [comment]
I'm really not a fan of automated code formatters for several reasons.
1- if everyone who works on the code reformats it the way _they_ want, the code shifts heavily at each pull request, making the maintainer job's harder when it's supposed to be made easier by said tools.

2- they are often inexplicably inconsistent. let me give an example here  (line numbers are the new ones) : 
entities.py:L39 : change the format to have spaces around equals sign. 
entities.py:L79 : change the format to _remove_ spaces around equals sign. 
entities.py:L938 : remove the existing format (equals signs right aligned)
entities.py:L361, lims.py:L32 : Add a dubious new line
entities.py:L91 : Remove a newline that's as dubious as the previous one. 
entities.py:L220 :  break down the line for seemingly no reason. 
lims.py:L196 : what is even the point of this ?
The rules are different for each code formatter and I really, _really_ do not want to have to cater to everyone coming in with their own rules. 

3- they literally make the pull request impossible to read if it contains anything else. If there is an undocumented change in this pull request, I'm very likely to miss it, because the diff is over a thousand lines. 

Now, I would accept the equals changes, even if they are not consistent, since they weren't consistent to begin with. The line adds / breaks are minor stuff, i'm not happy about it because it creates noise, but I don't mind _that_ much. 
However, removing the human readable format of the class arguments is not something I agree with. I don't care wether the automated tool likes it or not. I recently rejected a PR  (for another repo) for the exact same grounds, and unless you have excellent reasons for why we should use that specific code formatter, and why this way of writing class attributes is not desirable, I'll stand by that.

If you're ready to change that, I'll have a look again, but please, don't run automated formatters on code that you're going to send to upstream.

**Comment by tcezard** [comment]
The code reformatting follows the PEP8 standard which should be consistent thorough.
The formatting around operator is covered in the [other recommendation section](https://www.python.org/dev/peps/pep-0008/#other-recommendations) . The confusion arise because equal is used as the assignation operator (with space) and as keyword argument (without space). I personally think it is a nice way of distinguishing the two.

I agree with the fact that it make the PR very difficult to review and I apologise about that, but it is the reason why I do the reformatting in its own PR without any functional change. The Unit tests should help preventing any functionality to break.

This said, [PEP8 does come in the way of readability](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds) sometime and the right alignment is a good example of that. 
I'll have a look at cleaning the reformatting

**Comment by Galithil** [comment]
The PEP8 limits lime length at 79 and docstrings at 72 (which is silly, in my opinion), where you tool seems to have gone for 117 on entities.py line 119, so here's one instance where the PEP8 is not being followed...

Also, the PEP8 has very vague rules concerning newlines : 
```Extra blank lines may be used (sparingly) to separate groups of related functions. Blank lines may be omitted between a bunch of related one-liners (e.g. a set of dummy implementations).
Use blank lines in functions, sparingly, to indicate logical sections.```

but it seems that your tool has its own rules set up.

Once again, that is why I dislike these tools : they often take liberties that no one can see as they rewrite 80% of your file, and you're left to just hope that they did their job properly. 
Also, reviewing formatting changes is not exactly the most productive thing in the world. 

I'll wait for the next commit.

**Comment by Galithil** [comment]
Okay, looks good. is there anything else you want to take care of in this PR ?

**Comment by tcezard** [comment]
Sorry I'm rebasing cause there are too many small commits

**Comment by tcezard** [comment]
Should be good now.

**Comment by Galithil** [comment]
Okay then.

**Comment by Galithil** [comment]
pypi seems to have some internal troubles. I did upload the latest version, but I cannot ensure its integrity, as I get a 500 server error : 
https://bitbucket.org/pypa/pypi/issues/262/getting-500-error-when-uploading-python

You might want to be careful when using pypi to install.

**Pull request merged**
