### PR TITLE
Update selected containers on new placement

### PR DESCRIPTION
**Pull request by Galithil**
This takes care of the last failing test. 
The main issue I have with these tests is that they compare xml strings, and after I play with them through Etree, the whitespaces are not the same, therefore string comparison fails. I couldnt find a quick solution to compare two xml trees, so I compare the strings without spaces. 
If anyone has a better solution that doesnt requires to write an xml comparator, I'm interested.

This doesn't handle "creating a placement from scratch" but I'm really not sure of the necessity of such a thing. Since you cannot create a step from naught with this repo, I don't think it's needed straight away.

### CODE REVIEW

**Comment by Galithil** [comment]
@tcezard what do you think ?

**Comment by tcezard** [comment]
That looks good but I didn't look in the detail yet.
I have however added a small comparison function for ElementTree which should help get over the string comparison issue. in #163

**Comment by Galithil** [comment]
@tcezard  Your comparing function is interesting, but comparing text and tails causes the exact same problem  as comparing strings : it compares meaningless whitespace and the assertion fails.
7d6c850c951d4685843e8a6fee9aeaef8c04c0ce takes care of that.

**Comment by tcezard** [comment]
Thank you for this. That looks good!

**Pull request merged**
