### PR TITLE
Reagent labels 2

### PR DESCRIPTION
**Pull request by paalmbj**
Corrected version of the pull request

Three commits:

    First: moves the access to the index sequence of a ReagentType object into a property, so it supports lazy fetching.
    Second: uses a custom set class to represent the reagent labels of an Artifact, so it's now possible to add and remove reagent labels. Since this changes the container for reagent labels from a list to a set, I added a getitem method to support numeric indexing, for compatibility.
    Third: removed the Reagent_label class which I believe is provably not being used anymore

### CODE REVIEW

**Comment by Galithil** [comment]
Unfortunately, I have an issue with this on a more structural level. 
Switching a List for a set is not trivial, and in our use cases, I'm afraid it will prove an issue. 

For instance, we rely on all of the properties of our objects to be JSON serializable, as we make out own JSON data model of the data we get from the LIMS. 
A list is easily JSONified, a set, unfortunately, is not, especially when it's not a standard one. 
I looked around a bit, but the tricky part here is that we can't have a custom json encoder either. 

If you manage to find a way to let json accept the mutable set as jsonifiable, sure, but it would break all of our information flow otherwise.

**Comment by paalmbj** [comment]
Thanks for taking the time to check it. I'll see if I can think of a solution.

**Comment by Galithil** [comment]
I think it should work if you were to change the behaviour of the __repr__ method.

**Comment by paalmbj** [comment]
I couldn't get it to serialize with json.dumps even with a custom __repr__ or by subclassing MutableSequence instead of MutableSet (and defining __repr__ on that). Subclassing list itself would introduce too many functions. I don't see a solution for this right away, so you can probably close this pull request.

**Comment by Galithil** [comment]
Closing this as this is not mergeable anymore.

**Pull request closed without merging**
