### PR TITLE
Changes to get_batch and adding put_batch

### PR DESCRIPTION
**Pull request by paalmbj**
Second attempt at a pull request (see: #125). Fixed a bad mix-up of URIs and XML data.

Known issues: For Artifact objects, get_batch returns new objects with a different URIs than the ones in the argument. E.g. for an argument with URI:

    http://sandbox-lims.sequencing.uio.no:8080/api/v2/artifacts/92-832

it returns an Artifact with URI:

    http://sandbox-lims.sequencing.uio.no:8080/api/v2/artifacts/92-832?state=533

This is different than calling Artifact.get(), which will not update the URI.

### CODE REVIEW

**Comment by Galithil** [comment]
I already reverted, actually.

**Comment by Galithil** [comment]
Only the artifacts have a state, and I added a 'stateless' property to get around it.

**Comment by paalmbj** [comment]
Accidentally reverted everything. Will update later.

**Comment by paalmbj** [comment]
I think I've found a decent compromise between the various special cases. It has been running in production for a while at our site so it should be stable. 

The problems were:
- It should not update the uri of entities, even though returned artifacts may have a ?state parameter and the one in the request doesn't. If it was updated, that would mess with caching and comparing identical artifacts. When using a non-batch call to get the content of an entity, i.e. Entity.get(), the uri is not updated.

This was solved by matching the LIMSIDs of the returned entities against the LIMSIDs of the function argument, i.e. the requested entities. So we don't call the constructor, instead just fill in the root properties of the arguments.

- When requesting the same entity multiple times in the argument list, only one instance is returned by the API. The function now acts the same way as the API call, both for cached and non-cached entities, because it returns the values of a LIMSID->entity mapping.

- When requesting different ?state of the same artifact, or one uri with ?state and one without, the API would return a single result with one of the states (not sure if it was the max state number or an arbitrary one). This function raises an exception in this case.

- The order of the entities in the returned list may be scrambled, but this is also the case for the API. 

There's been a lot of commits with back and forth, so please look at the "files changed" page for an overview of the changes.

**Comment by Galithil** [comment]
It looks like this behaves properly for our system as well.

**Pull request merged**
